name=TimeDisplayLibrary
version=2.0.0
author=Toby Brandon
maintainer=Tjpropandbuild@gmail.com
sentence=A library for controlling a four-digit NeoPixel seven-segment display.
paragraph=Display any number from 0 to 9999 on a 28-pixel four-digit seven-segment NeoPixel display, with colour and brightness control.
category=Display
url=https://github.com/sumkindafreak/TimeDisplayLibrary
architectures=*
depends=Adafruit NeoPixel
